### ISSUE TITLE
Rename contact overview tab

### ISSUE THREAD

**Issue by basilesimon** [beabee-communityrm/beabee-frontend#130]
From Tobi:

> Second tab "Information" should maybe be called "Kontaktdaten", but I'm not sure which line in the spreadsheet it is, otherwise I would have changed it already. 

![image](https://user-images.githubusercontent.com/5701152/158385251-476e2527-27c7-4944-9b8f-543e5fc6e473.png)

**Comment by wpf500** [comment]
Done a while back
