### ISSUE TITLE
QA: mobile layout for callout answer page

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#131]
![image](https://user-images.githubusercontent.com/122730/158406295-d3722c80-beba-4eab-a0d6-e57f3f6b7110.png)

Added [one screen](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=80a83000-8349-11ec-b868-f579dbfb6f82&section=interactions&index=0&share-id=aae401f0-a46e-11ec-a0b4-765163de8d2d) to show the layout adjusted to a small viewport width:
- headings are smaller (mobile header sizes added to design docs)
- below the callout title, callout status (open/ended) and _You answered this callout<3_ are stacked
- form buttons (like submit, at the bottom) resize to 100% width
- link "Back to callouts" is at the bottom, above the footer

**Comment by wpf500** [comment]
Looks good :+1:
