### ISSUE TITLE
Feedback required: Admin dashboard

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#136]
![image](https://user-images.githubusercontent.com/159868/158796197-e5b531fb-3a18-4142-bcad-872ef457f1f3.png)

As we're putting together the spec for the admin dashboard, we realised there should be a set of links/references to more information and support for Beabee admins. We've opened a space for this (the darker rectangle) and were wondering what to include, e.g.

- handbook
- contact support
- read more about ____

This is mostly because the current set of options/metrics is limited, resulting in a pretty scarce layout; looking into other examples, a common thread is to provide quick informative pointers somewhere.

If you think this makes sense, what's the links/pointers we should include here?

Reference: [admin dashboard Mural](https://app.mural.co/t/beabee6721/m/beabee6721/1647425778580/170dfb53675095b843e4c33079f6e99e5db2f318?sender=u211bfacb997554e96f099008)

**Comment by TobiasHauswurz** [comment]
I think the biggest problem here is, that we don't really have that much content, that could go in here. And what we have is in german mostly. We don't have a support website with guides etc. now. This will not happen before Perugia. But I made a list with ideas for german and english:

German: 

- My contact: tobias.hauswurz@beabee.io
- beabee Online-Class at the Reporterfabrik of CORRECTIV: https://akademie.reporterfabrik.de/courses/course-v1:Reporterfabrik+304+2021/about
- Our german wiki (which is not really up-to-date): https://wiki.beabee.io/community-guides-german/
- Link to buy our handbook: (not there yet)

English: 

- My contact: tobias.hauswurz@beabee.io
- hmmm....

**Comment by rlafuente** [comment]
OK we have a bit of a dilemma here then :) On one hand it'd be great to have more content for the dashboard to look more populated. On the other, we need to have content for this to work!

@julia-hildebrand @wpf500 should we just go ahead without the dashboard links section? Or do you know of any other element/guide/section we could add to the dashboard?

**Comment by rlafuente** [comment]
Refining the layout after a quick call today with Julia & Tobi:

![image](https://user-images.githubusercontent.com/159868/159960027-266e044e-9e35-48c8-8afd-3a853343c6fb.png)


We're not sure about how much the Slack banner should stand out, or whether the support link should be more highlighted, so we're putting this version out to help find the way. Any copy corrections+improvements are welcomed as always!

**Comment by basilesimon** [comment]
Commented on this during standup this morning:

- Love it!
- If you wanted the "big numbers" to be bigger and more bespoke, I think we'd be happy to consider this if there's time. The present version is "low friction" (Ricardo) and that's kind of you :)

**Comment by aiscarvalho** [comment]
We updated the dashboard to include big numbers! [It's in the same spec](https://design.penpot.app/#/view/f8f23980-a530-11ec-a0b4-765163de8d2d?page-id=3a291521-3d7d-11ec-a943-23056af0be2f&section=interactions&index=0&share-id=7e48a400-b01e-11ec-8896-765163de8d2d), together with the low friction version.

![image](https://user-images.githubusercontent.com/122730/160847458-d2815eae-b4ec-4779-a776-ef3f5e19f8ce.png)

**Comment by basilesimon** [comment]
I personally really like it :)

**Comment by wpf500** [comment]
Looks great, let's do it!

**Comment by wpf500** [comment]
My only comment is "Most recent subscriptions" isn't really the right language, it needs to be something like "Most recently joined" as we don't really use the term "subscriptions". However this can obviously just be adjusted during the implementation
