### ISSUE TITLE
Proposal: Remove callout confirmation step?

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#141]
We were looking into the move to unify the Callout Summary page and the last confirmation step when creating a new callout.

And we just thought that maybe we could do without the confirmation page? As a reminder, it's this one:

![image](https://user-images.githubusercontent.com/159868/159681815-665d7dcd-22e4-452d-8251-bffb251d9a52.png)

And this because:

- creating a new callout is not a decisive/definitive action, everything can be edited later
- it's one less config step = better UX
- it's less work for everyone = cheerful team

So the proposal would be: Remove the confirmation page; last step should just have a Create Callout button and move you to the "view callout details" page. Maybe include some reassuring copy like "you'll be able to edit everything before publishing your new callout".

What's your thoughts on this?

**Comment by wpf500** [comment]
Yeah definitely worth a try :). We can review once we have a working version of the create callout flow

**Comment by basilesimon** [comment]
Seconding what Will said :)

**Comment by rlafuente** [comment]
Great! We'll update the spec then.

**Comment by rlafuente** [comment]
Updated spec is [here](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=50d8b780-89c7-11ec-b79c-9eafb5cb1e0f)!
