### ISSUE TITLE
Support for several font-families

### ISSUE THREAD

**Issue by basilesimon** [beabee-communityrm/beabee-frontend#147]
Presently, `<body>` is set to follow `.body-font` (Open Sans by default).

While it is possible to specify additional fonts in `theme.json` (it's even implemented in `tailwind.config.js`, these declarations are not used in the app.

That behaviour feels unexpected to me, and was reported by Sascha on Slack.

[Here's an example reproduction of the behaviour](https://github.com/beabee-communityrm/beabee-frontend/commit/af725021b8301fbef89894456b3e7d46e6f0db01)

### Possible action routes
@beabee-communityrm/design would need to flag which UI elements follow `.title-font`, and the rest will follow `.body-font`.

**Comment by basilesimon** [comment]
We're even saying we can in the deploy readme:

> You can customise a title and body font.

**Comment by saschafoerster** [comment]
I really like, that I can now define two fonts. Just, the title-font is not appearing every-where, where I expect it. 
I guess some vue-files here where missing, especially around /join and the /auth-modules
https://github.com/beabee-communityrm/beabee-frontend/tree/main/src/modules/auth

I searched for some places (not shure these are all titles)

https://github.com/beabee-communityrm/beabee-frontend/blob/7a52e53c7d04d8e5d4472e7b770695a6d6fda2cb/src/modules/auth/login/LoginPage.vue#L3

https://github.com/beabee-communityrm/beabee-frontend/blob/7a52e53c7d04d8e5d4472e7b770695a6d6fda2cb/src/modules/auth/join/components/JoinHeader.vue#L10

https://github.com/beabee-communityrm/beabee-frontend/blob/7a52e53c7d04d8e5d4472e7b770695a6d6fda2cb/src/modules/auth/join/components/JoinNotice.vue#L8

I guess they just need a addition of "title-font"? :)

**Comment by basilesimon** [comment]
@saschafoerster fixed in incoming pull request: https://github.com/beabee-communityrm/beabee-frontend/pull/170

Thanks for the report.
