### ISSUE TITLE
Wireframe: post-signup dashboard

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#158]
A wireframe for the dashboard after signup with suggested actions and necessary actions ([penpot link](https://design.penpot.app/#/view/167be840-9008-11ec-bd38-efdb6fa63305?page-id=4fe6fd30-b4f8-11ec-a6b4-8bf5c7f95f90&section=interactions&index=0&share-id=592877f0-b5c2-11ec-862a-da95c03a630b)):

#### Dashboard:
![image](https://user-images.githubusercontent.com/122730/162251295-0e4aae05-7986-4bca-a2e2-76bf6c341a33.png)

#### Dashboard with notice (and completed or dismissed suggested actions)
![image](https://user-images.githubusercontent.com/122730/162251270-6cae1220-fb12-4ef3-92bb-e4c3d029d949.png)

We hope we've captured everything, let us know if there's something that could be added/changed :)

**Comment by aiscarvalho** [comment]
Today we had a great call and super useful feedback from Julia and Tobias. Here's a quick list of the updates and the revised wireframes:

- post-signup suggestions should all be _dismissable_. Options to provide: don't show this again; remind me later (shows in next login)
- after signup we'll use warnings to prompt admin for missing data/actions
- payment copy box: make it re-purposable. It's the place to show information regarding payment according to each newsroom situation. Some examples:
    - a default copy "we won't charge you yet"
    - you're paying X/month, next payment is in *Y of Mon of year*
    - you're a tester and won't be charged
    - include link to "edit payment details"
- remove "subscription" and use "new members"
- add illustrations to import contacts / create join form
- add estimated time to import contacts / create join form
- move support up and include Tobias portrait
- move "join slack" link down

![image](https://user-images.githubusercontent.com/122730/163005446-88d5885f-b611-4ed6-a441-ef1885e7e49a.png)

---
![image](https://user-images.githubusercontent.com/122730/163005662-02692cf7-1dd4-4276-b31b-b07e7d90ab08.png)

**Comment by wpf500** [comment]
I think this looks good for now. I worry a bit about the whole thing being dismissable, but maybe the notices will be able to cover the important stuff. I think this will be a lot clearer when we start implementing it and get a feel for it, so :+1:

**Comment by TobiasHauswurz** [comment]
Yeah, looks good for now. The thing about being dismissable: 

The idea behind it was, that there are some things a newsrooms might not want to do at all. Like connecting Mailchimp, set up a custom domain or import existing contacts. It would not be so nice to remind them forever, because they would never be able to make "normal" use of the dashboard...So maybe just some things should be dismissable and some not? And I think it's would need to be very clear where to find the options once dismissed...
