### ISSUE TITLE
Spec: Membership builder

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#165]
Here's the specs for 3 membership builder sections, which are previewed and annotated below. Here's quick links to the spec pages:

- [Join form](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=2)
- [Intro message editor](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=0&share-id=499e0380-c0c7-11ec-82c9-da95c03a630b)
- [Email editor](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=0&share-id=499e0380-c0c7-11ec-82c9-da95c03a630b)

General notes:
- Navigation happens on the tabs on top
- The overview page would have the TODO checklist for launch and the Go Live option

## Join form

Preview:

![image](https://user-images.githubusercontent.com/159868/164278241-1aed32d1-c81c-4b14-9deb-36493f73374d.png)

Spec: [see on PenPot](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=2)

Relevant notes:
- The options for the "Starting default amount" dropdown would be determined from the amount options the admin has set for monthly and yearly payment.

## Intro message editor

Preview:

![image](https://user-images.githubusercontent.com/159868/164278997-f5571e5d-e276-4918-9239-f658c2e6c830.png)

Spec: [see on PenPot](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=0&share-id=499e0380-c0c7-11ec-82c9-da95c03a630b)

Relevant notes:
- The preview rectangle shouldn't extend vertically as far as the preview shows; we'll fix the PenPot spec, check it for the most up-to-date version
- Template placeholders (e.g. user first name as `*|FNAME|*`, like Mailchimp) could probably be placed using dedicated buttons. But for a first go, having help text explaining this should suffice.
- The textarea controls are probably determined by the frontend library, which is why we left those blank in the spec
- It's called "Intro message" to distinguish it from the welcome emails

## Email editor

Preview:

![image](https://user-images.githubusercontent.com/159868/164280175-02a9ce9c-baca-4e8f-8f58-2dbf60432079.png)

Spec: [see on PenPot](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=06c46321-bbf8-11ec-862a-da95c03a630b&section=interactions&index=0&share-id=499e0380-c0c7-11ec-82c9-da95c03a630b)

**Comment by wpf500** [comment]
Looks good in general. I've been chatting with @basilesimon and we think the create callout style stepper component is a cleaner way of implementing the steps (insetad of tabs), so we're going to start with that approach but can review when you're back as it doesn't affect building the core forms for the page.

**Comment by aiscarvalho** [comment]
We're onboard with trying the callout stepper component! And can adjust the spec during implementation if any layout issue arises.

**Comment by wpf500** [comment]
@aiscarvalho did you reopen this issue for a reason or shall we close it?

**Comment by aiscarvalho** [comment]
@wpf500 yes. At the time reopened it because we closed it before review and Tobias couldn't comment. I'm closing it since review is done :)
