### ISSUE TITLE
Spec: Admin dashboard (revised) + empty sections

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#166]
Penpot links:

- [Revised dashboard](https://design.penpot.app/#/view/f8f23980-a530-11ec-a0b4-765163de8d2d?page-id=3a291521-3d7d-11ec-a943-23056af0be2f&section=interactions&index=0&share-id=19efd3f0-c0c9-11ec-82c9-da95c03a630b)
- [Dashboard with empty sections](https://design.penpot.app/#/view/f8f23980-a530-11ec-a0b4-765163de8d2d?page-id=3a291521-3d7d-11ec-a943-23056af0be2f&section=interactions&index=0&share-id=19efd3f0-c0c9-11ec-82c9-da95c03a630b)

## Revised dashboard

![image](https://user-images.githubusercontent.com/159868/164282401-46a46d05-face-40c7-9e24-4f75601a4318.png)

The dashboard design was updated according to Product team's feedback:

- Payment copy box: make it re-purposable since many testers will have special deals and newsrooms will eventually start paying!
    - option 1: a default copy "we won't charge you yet" for normal users
    - option 2: text for "special deal" newsrooms
    - option 3: you're paying X/month, next payment is in *Y of Mon of year*
    - include link to "edit payment details" always
- move support up and include Tobias
- move "join slack" down

## Empty sections

Example of a totally empty dashboard:

![image](https://user-images.githubusercontent.com/159868/164282478-f5a21941-df22-4d6c-b1d7-df4034ba65cf.png)

**Comment by basilesimon** [comment]
I think it's really good foresight to include the box aiming to inform admins about their deal, when it would end, etc.

Let's just make sure to map out the copy (in English at least) so we can get a sense of the data we need to pull out to make this happen :)

**Comment by wpf500** [comment]
Looks good. One thing: I like the style Stripe/GoCardless use for their empty dashboards where the "Numbers for the last 30 days" bit just shows 0s. I think it suggests opportunity and the exciting prospect of things to come: "you could get revenue and have members". What do you think?

Agreed with @basilesimon about the payment text but I don't think we need to do that in this task as this should just be about the empty state

**Comment by aiscarvalho** [comment]
We agree! We've updated the spec to display 0s in the stats while there's no data available:

![image](https://user-images.githubusercontent.com/122730/168042230-4465e54b-3f6b-4131-8ee3-33d89faa25e4.png)
![image](https://user-images.githubusercontent.com/122730/168042168-ec2323dc-452e-4561-b2d2-afb545bda412.png)

**Comment by wpf500** [comment]
Great, closing this then :+1:
