### ISSUE TITLE
Wireframe: Legal agreements page

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#182]
This follows from the [requirements](https://app.gitbook.com/o/-MLm62K6BHNeK5d-nHW5/s/-MLm5pPMozvqHfx_eia1/docs/feature-requirements/legal-requirements-for-self-onboarding) for the page where newsrooms accept our agreements.

![image](https://user-images.githubusercontent.com/159868/167603296-902b6026-b890-4829-b8b3-c34a83a50f99.png)

[Penpot doc](https://design.penpot.app/#/view/167be840-9008-11ec-bd38-efdb6fa63305?page-id=d170c3d0-d042-11ec-a5c9-cd3df845a6bc&section=interactions&index=0&share-id=71b7b3d0-d048-11ec-ab9e-75f6b8214121)

For now it's about confirming which elements should be on the page. We can tweak the copy later (and do a closer legal review), and layout will also be straightforward.

(we were thinking of keeping this issue for the spec + implementation and later change the title as we go through each step)

**Comment by TobiasHauswurz** [comment]
Hmm, I'm actually not sure if this has to be a page on its own. I think this should go into this one, if we just add the missing legal parts: https://github.com/beabee-communityrm/beabee-frontend/issues/140 

Name and name of the organisation are already in there, so we would just need to add the address bit and the legal bits about the agreements to the bottom of this page. 

(I think "name of the authorised representative" isn't that important to have extra. Let's just assume that someone setting up beabee is authorised to do so by the company which he/she is working for.)

**Comment by TobiasHauswurz** [comment]
We already have some "legal stuff" at the end of #140. So maybe we can just put what is legally required under the "Almost done" part.

**Comment by aiscarvalho** [comment]
Good call! We integrated the legal details in the newsroom signup form, see below :)  
[Spec link](https://design.penpot.app/#/view/167be840-9008-11ec-bd38-efdb6fa63305?page-id=7c149280-9ef2-11ec-8243-fb3945d660a4&section=interactions&index=0&share-id=312387e0-d2d2-11ec-ab9e-75f6b8214121)

![image](https://user-images.githubusercontent.com/122730/168319289-2bd17fca-1562-462c-8cb9-ca0dc13b5827.png)

**Comment by TobiasHauswurz** [comment]
Looks good :)
