### ISSUE TITLE
Most elegant way to deal with distinct empty states on the frontend?

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#186]
This is more a way to articulate the problem and get @wpf500's perspective on how to proceed here.

Problem: We're now adding messages for empty widgets (e.g. tables, lists, numbers) and the contacts page turned up a small dilemma: there can be more than one reason for the table to be empty, which will require different messages to the user. In the case of the contacts page, we can have two empty states:

- Totally empty (zero contacts present), in which the message would invite the user to add and/or import new contacts
- Empty search results, in which the message should explain that there's no results, maybe with a quick link to clear the filter or search query, and another to add a new user

To solve this elegantly in Vue, I think (perhaps naively, you tell me :) that components that need an "empty" message could have a slot named "empty", which is filled according to context. This way we could support more than one possible empty state, as outlined above.

Does this make sense? Or is there a Vue/JS/* feature that would better deal with this?

**Comment by wpf500** [comment]
If I understand you correctly this would be adding a named slot to `AppTable` then defining the logic for which message gets shown in that slot for each use of `AppTable`? Sounds like a lovely solution to me :)
