### ISSUE TITLE
Fix join flow form element regular colours

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#19]
The current join flow form is not using the regular colour, as defined in the design spec (see here [step 1](https://design.penpot.app/#/view/a0f95530-bef2-11eb-9a82-c13c371b4289?page-id=566d15e0-c2b9-11eb-ae24-233497286712&index=0); [step 2](https://design.penpot.app/#/view/b59ef0e0-cf5e-11eb-abea-1491b30edcfb?page-id=4b6fa5f0-ceb6-11eb-b71d-2398648e5b9e&index=0)).

**Comment by wpf500** [comment]
@aiscarvalho is this resolved now?

**Comment by aiscarvalho** [comment]
Yes, all colors are in the correct place. Thanks!

Not a blocker at all, but we couldn't help but notice that the amount component selected and hover are not using the correct shade of the secondary color. We'll fill an issue just to keep track of it.

**Comment by aiscarvalho** [comment]
Not sure about the protocol here. I'll close this issue as it is solved :)
