### ISSUE TITLE
Spec: delete callout

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#193]
We updated the callout spec to document the _delete callout_ action. It follows the same pattern used in _delete callout responses_: a modal dialog asking for confirmation and warning the user the change is irreversible.  

![image](https://user-images.githubusercontent.com/122730/169074028-d13e7e1c-b387-4f04-820a-d41708e1c68b.png)

[Delete callout - direct penpot page link](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=74d1b8c0-5cff-11ec-826f-e949c75b760d) - direct link to page 22.  More: [delete callout responses](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=9ecc5080-850a-11ec-b8ce-3dfd811f2f5f&section=interactions&index=0&share-id=a49f8ca0-d6bf-11ec-ab9e-75f6b8214121); [full callout spec - penpot](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=4a449480-5910-11ec-8ccc-4b86b12c67d6&section=interactions&index=0&share-id=6ab51210-d6bc-11ec-ab9e-75f6b8214121).

Do you think the warning text works well? 
Were not sure how we could mention of things that will stop working/existing considering some callout might not have them (for example, draft callouts without responses).

**Comment by wpf500** [comment]
Yeah I think this looks good, nice and simple :+1:
