### ISSUE TITLE
Spec: replicate callout

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#194]
@wpf500 we went with the approach to auto-generate a new unique slug and title for replicated callouts, by adding a suffix like **_- copy 1_**. For example, a callout titled _Help needed!_ when replicated would become _Help needed! - copy 1_; a slug `help-needed` would become `help-needed-copy-1`.

When a user replicates an existing callout she/he is taken to the edit callout interface where they can review and update the information. We decided to show step 1, in the edit interface, since most information probably needs to be edited besides the title and slug.

By default replicated callouts are saved as drafts and the user can then publish them.

Here's a screenshot of the edit callout screen after replication. A message is displayed to inform the user replication was successful and that the replicated callout is a draft ready to be edited:

![image](https://user-images.githubusercontent.com/122730/169264533-66919b50-2f71-4577-88ec-03f45c6ab8fa.png)

[Replicate callouts spec](https://design.penpot.app/#/view/e35a4dc0-1ae2-11ec-9c71-4a8af25a7bed?page-id=28285060-d757-11ec-967a-a7336013a9fc&section=interactions&index=1&share-id=68256310-d757-11ec-ab9e-75f6b8214121).

**Comment by wpf500** [comment]
Yeah I think that approach is much better/simpler than the legacy app :+1:
