### ISSUE TITLE
Spec: newsroom signup

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#201]
A design spec for the newsroom signup process, following-up on the wireframe and the Essen work session.

Our guiding principles for the newsroom signup up were: make a one page form that is visually compact and easy to fill out.  To make the form layout compact, in desktop, labels and inputs are placed side by side. We mocked the form as a page from beabee's main website, with the top navigation as frame.

The payment section UI is a placeholder since tech requirements are not yet fully fledged; the legal section is also missing text.
We mocked the form as a page from beabee's main website, with the top navigation as frame.

Screenshot below + [penpot link](https://design.penpot.app/#/view/cf242f00-d785-11ec-ab9e-75f6b8214121?page-id=4ecca760-d785-11ec-8d94-b740c212d49e&section=interactions&index=0&share-id=05271a80-dc3c-11ec-8d51-75f6b8214121) (the spec has only one page as shown in the screenshot).

![image](https://user-images.githubusercontent.com/122730/170311226-efc2c3b9-7cdb-435c-b739-b1d080bec253.png)

**Comment by wpf500** [comment]
Looks great. A few comments:
* I think we might need to add a language dropdown unless we default to English?
* I don't think we need the organisation's address, unless this is for something legal?
* Could you spec out how the subdomain "click to edit" would work?

**Comment by aiscarvalho** [comment]
We updated the spec to include the language dropdown and the subdomain edit; and kept the address fields because of the legal requirements:

![image](https://user-images.githubusercontent.com/122730/172892129-a18a5198-c09d-4860-9cda-07711eb52ed8.png)

**Comment by wpf500** [comment]
Closing as this has gone through review
