### ISSUE TITLE
Spec: Import contacts flow

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#223]
Importing contacts flow: [spec in penpot](https://design.penpot.app/#/view/ec5354d0-ed55-11ec-8abe-f940e3befd53?page-id=3a291521-3d7d-11ec-a943-23056af0be2f&section=interactions&index=0&share-id=da550fd0-f23c-11ec-b774-f940e3befd53)

While doing the design we decide to:
- add a step to the side navigation for the screen where we show matching contacts and errors (it's clearer for navigation purposes)
- include the option to create a segment for the imported contacts in step 2 as it simplifies the flow (and the UX and the implementation):
![image](https://user-images.githubusercontent.com/122730/176144646-a01d57a0-f429-4a1c-bca4-4256b14d8fe7.png)

Step 1 - import user without payment data:
![image](https://user-images.githubusercontent.com/122730/176144767-80d2e7bc-933b-45b0-8000-11fea3fa70b2.png)

Step 2 - map data
![image](https://user-images.githubusercontent.com/122730/176144935-5b1840dd-3a36-4a85-94ba-11dfe93d4cd9.png)

Step 3 - contacts with matching emails and errors
![image](https://user-images.githubusercontent.com/122730/176145037-8a5167be-fe24-4a68-b558-4b36f27752db.png)

Step 4 - preview import (for the preview import tables we would favor using scroll instead of pagination)
![image](https://user-images.githubusercontent.com/122730/176145454-4486e21b-e853-4a7d-8928-6b475638344d.png)

Import conclusion:
![image](https://user-images.githubusercontent.com/122730/176153348-fc034d1e-6a55-47a3-959f-f37182c60b27.png)

![image](https://user-images.githubusercontent.com/122730/176153514-7002b44e-21ff-48a7-8228-bd1f1818316e.png)

**Comment by wpf500** [comment]
LGTM :+1:

**Comment by TobiasHauswurz** [comment]
Looks nice! Twi things from my side: 

- Not sure about that newsletter bit, i think this could be much more complicated. Is the idea to send everyone from that list an automated email with an invite? Where is this invite leading them to, then? Would we need something like a subscription form then? Another use case could be, that they already have the permission to send them newsletters. Or possibly many other, don't know...

- Is it intentional that the contact list has different columns than the ones we are using so far? Member and Amount is new...

**Comment by aiscarvalho** [comment]
- we'll leave out the newsletter bit for now. We agree that bit is tricky; we can't add people to the newsletter without their consent and there might be people that are already subscribed. Plus, sending an invite would only work if we had configurations for a connection to MC.
- Good catch :) we re-used the contact list from the original contact list spec (which is a little different from what's implemented). We updated the columns so that they match.

**Comment by wpf500** [comment]
Going to mark this as done as we can clean up any other issues during implementation
