### ISSUE TITLE
Spec: Payment history markers

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#224]
In order to mark payments that failed, as well as future/upcoming payments, we propose a simple style to highlight them, with two alternatives for the desktop view.

![image](https://user-images.githubusercontent.com/159868/176161402-7b4c3ea3-1fc5-4354-ac64-82aef3cec31a.png)

Mobile/narrow view should have a tooltip or tappable marker to explain its meaning.

We're not sure of how eagerly we want to call the user's attention (e.g. failed payments, do they need action?) so we put out this as a v1 for some back-and-forth regarding the priorities for this small feature.

**Comment by wpf500** [comment]
I think simpler is better (the one on the right), but is green the right colour for upcoming payments? At a glance it looks more like a success state which is confusing (especially on mobile). Could we go for a lighter shade of body text colour instead?

**Comment by rlafuente** [comment]
Good call, here's an updated view:

![image](https://user-images.githubusercontent.com/159868/176650203-5117ab3a-8517-4bde-94d4-0d459f84d10f.png)

**Comment by wpf500** [comment]
Implemented by https://github.com/beabee-communityrm/beabee-frontend/pull/227
