### ISSUE TITLE
Wireframe: newsroom settings

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#229]
See the [wireframes on penpot](https://design.penpot.app/#/view/3c1804e0-f7ae-11ec-8f45-75f6b8214121?page-id=3c1804e1-f7ae-11ec-8f45-75f6b8214121&section=interactions&index=0&share-id=af7c84b0-fd35-11ec-8f45-75f6b8214121) or below (we're including screenshots of all pages here).

1. General
![image](https://user-images.githubusercontent.com/122730/177575926-72023ab1-61b5-4326-9770-ce5922eba75f.png)

2. Domain
![image](https://user-images.githubusercontent.com/122730/177574189-a84fca37-7b4d-4d3f-8f4a-1d832ef175a0.png)

3. Theme
![image](https://user-images.githubusercontent.com/122730/177574357-8faf46fb-77d7-45c4-9c7e-04b8761ba25d.png)

4. Emails
![image](https://user-images.githubusercontent.com/122730/177574438-5a169171-f83a-4e75-8474-205ddeb3b898.png)

We left out the _Admins_ section we had suggested during the requirements session. Since it is in the Contacts' page that the user can add other users and configure their roles we think it would make more sense to have this information there. We can include a filter for the _admin_ role in the Contacts' page.

**Comment by aiscarvalho** [comment]
One more note: we were wondering about the need for social sharing definitions since all pages will only be accessible to registered users.

**Comment by saschafoerster** [comment]
@aiscarvalho How about the join-page? I think this is the only page, where it's worth about the design in social sharing.

**Comment by aiscarvalho** [comment]
@saschafoerster yes, that's a good one! And in that case it would make sense to have this together with the join form editor.

**Comment by wpf500** [comment]
@aiscarvalho I think we needs some default share settings so if any URLs do find their way onto social media there is at something to display. We could combine these with the join share settings so most URLs (except callouts) get a join message if a URL is shared?

**Comment by wpf500** [comment]
@aiscarvalho the domain settings don't quite work I think. The user still needs to install four DNS records whether they use a custom email domain or not. There are basically three scenarios for the domain/email configuration:

1. User chooses community.newsroom.org as their domain without a custom email domain:

CNAME community -> deploy1.beabee.io
CNAME em1234.community -> xxx.sendgrid.net
CNAME s1._domainkey.community -> s1.xxx.sendgrid.net
CNAME s2._domainkey.community -> s2.xxx.sendgrid.net

2. User chooses community.newsroom.org as their domain and newsroom.org as their email domain:

CNAME community -> deploy1.beabee.io
CNAME em1234 -> xxx.sendgrid.net
CNAME s1._domainkey -> s1.xxx.sendgrid.net
CNAME s2._domainkey -> s2.xxx.sendgrid.net

(Note the lack of .community on the last 3 records)

3. User chooses community.newsroom.org as their domain and anotherurl.org as their email domain:

This would mean they need to create the DNS records in two different places. I don't think we we should allow this. I can't think of any scenarios where it makes sense to get emails from support@anotherurl.org for a website at community.newsroom.org

So if we only allow 1. and 2. then it's basically the same records with just a small difference. I think it would make more sense to ask about a custom email before showing DNS records, and just show one table of records. Not sure if I've made any sense there so can jump on a call to clarify if needed.

--

Quick thought on the footer links: The privacy/terms/impressum URL are also shown in emails and a few other places so aren't just "footer", does that matter? Maybe that distinction doesn't matter to the user and they are fine in the "footer" section?

**Comment by aiscarvalho** [comment]
We updated the domain setup wireframes but would welcome your feedback. It's a tricky set of combinations but from what we understand this might cover all possibilities:

- a newsroom that uses our URL but wants to send emails from their custom domain:
![image](https://user-images.githubusercontent.com/122730/178703118-3125f712-59ee-4a90-8e8a-ccb8cb0ddfe7.png)

- a newsroom that uses a custom domain and wants to send emails from their base domain:
![image](https://user-images.githubusercontent.com/122730/178703189-abe4a17c-3bcf-4837-b027-b8019b7d3942.png)

Footer: to make it simple, could we have the same content everywhere (app and emails)?
We can add text in this part to explain where the links will be shown. It's always helpful :)

For the sharing data, we agree that it's good to keep it in the general settings, to set a default for any link that gets shared.  
If you think it would make sense to have a specific share data for the join form, we can add it there too.

**Comment by wpf500** [comment]
I think this covers the use case we want to offer for email domain settings :+1:. Technically we could give them the option of sending from *any* domain that sits within the base domain, (e.g. members.newsroom.io, email somethingelse.newsroom.io) but that seems a bit mad in any case. Let's stick with this.

The links are already shared between all the places, I was just making what I think wasn't a very useful point about the fact that they don't *just* appear in the footer. I think your suggestion of a note saying where it will be shown is perfect.

LGTM :+1:

**Comment by TobiasHauswurz** [comment]
Just leaving some thoughts: 

- Is there really a Use case for people not using their own URL but are then super keen about the Emails coming from their domain? Maybe it would make things easier, if we just offer that, when using a custom domain. Having too many different options could overwhelm people without any technical background.

- Referring to this: Maybe we could add some kind of hint at the DNS bit like „Don't panic, it's really easy, read our little guide and if that doesn't help contact Tobi. Even he is now capable of doing it.” 

- And is it clear to anyone, that ticking the "yes, send emails from my base domain" changes the records that are already shown below? Maybe it should be a step and the records shouldn't be shown until the admin answers the question if he wants to use his domain for emails? "Do you want to send emails from your domain? Yes / No" and then the records appear.

- I think terms of service URL doesn't need to be mandatory.

**Comment by wpf500** [comment]
Some good points there I think @TobiasHauswurz. I've also realised that there will need to be a button to "submit" their chosen domain anyway as the server will need to generate the DNS records, so we can't actually show the DNS records at the start

**Comment by aiscarvalho** [comment]
We agree 100% with @TobiasHauswurz point about simplifying the domain and email setup by removing the option to "send emails from a custom domain" when using an URL provided by beabee. Also agree with adding more copy to make this part less intimidating :)

@wpf500 to generate the DNS records maybe we just need to move "Save button" below the email question (and rename it :):
![image](https://user-images.githubusercontent.com/122730/179025649-876fda75-64f1-42f3-a0ac-5323ed9eb146.png)

All these steps in the domain setup will be sequential -- it won't all be visible from the start. We'll show this in the spec!

**Comment by wpf500** [comment]
@aiscarvalho the server will need to know both pieces of information (domain and email domain) before generating the DNS records so probably makes sense that they are just in the same step?

We can see how this plays out during implementation too so I think these wireframes are good enough to become a spec :+1:

**Comment by aiscarvalho** [comment]
Good call!
We'll take this into account when designing the spec (domain and email domain in the same step).
