### ISSUE TITLE
Spec: edit payment methods in join form

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#234]
[Spec for editing payment methods in the join form](https://design.penpot.app/#/view/06c46320-bbf8-11ec-862a-da95c03a630b?page-id=970f83e0-038a-11ed-8903-77092518f855&section=interactions&index=0&share-id=b255efe0-038a-11ed-9552-f940e3befd53).

A drag and drop interface to quickly select and order the accepted payment methods:

![image](https://user-images.githubusercontent.com/122730/179020646-a9c1bbb9-08f6-4374-8751-87b77be17248.png)

![image](https://user-images.githubusercontent.com/122730/179020733-45aa0bf6-e452-47f6-aa33-bf7db0ca9935.png)

**Comment by wpf500** [comment]
Look's great! :+1:

**Comment by TobiasHauswurz** [comment]
Yes, looks great. Nothing to add.
