### ISSUE TITLE
Spec: Newsroom settings

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#238]
This section has 4 subsections:
- General settings
- Email settings
- Domain settings
- Theme settings

[Open in PenPot](https://design.penpot.app/#/view/aad80030-0828-11ed-9552-f940e3befd53?page-id=aad80031-0828-11ed-9552-f940e3befd53&section=interactions&index=0&share-id=60fbd800-1337-11ed-817f-f940e3befd53)

## General settings
![settings   general](https://user-images.githubusercontent.com/159868/182895428-28b38a65-f7a6-4273-aacb-5be0755bfdff.png)

## Email settings
![settings   email](https://user-images.githubusercontent.com/159868/182898393-3f6aadb3-347e-4621-baf8-43cb2944c307.png)

## Domain settings
![settings   beabee domain 1](https://user-images.githubusercontent.com/159868/182898427-1af7b891-693d-4f6c-b791-5488fa1a1b23.png)
![settings   beabee domain 2](https://user-images.githubusercontent.com/159868/182898432-7071bbc3-04b6-47a2-9153-f5c38621253b.png)
![settings   custom domain 11](https://user-images.githubusercontent.com/159868/182898452-6a3fafd6-f2ab-4f84-9d5d-06b22c85cc82.png)
![settings   custom domain 2](https://user-images.githubusercontent.com/159868/182898437-178067b6-f917-4cf0-9ba1-68a2eed9914d.png)
![settings   custom domain 3](https://user-images.githubusercontent.com/159868/182898442-93925f9d-c10e-4843-9b55-4ac7ee9617d8.png)
![settings   custom domain 4](https://user-images.githubusercontent.com/159868/182898448-65ad8dab-913f-441f-b543-17368b56ea17.png)

## Theme settings
![settings   theme](https://user-images.githubusercontent.com/159868/182898520-7f068d7f-500b-4707-936c-5c599f96623f.png)

**Comment by wpf500** [comment]
Looks good to me :+1:. I think some of the copy might need a bit of changing but we can do this in the implementation phase

**Comment by TobiasHauswurz** [comment]
Agreed, looks good besides some copy stuff.
