### ISSUE TITLE
Design review: change "text-primary" classes to "text-body"

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#263]
This is because both are supposed to address the same colors -- note that this is just for the "text-" classes

(this is mostly a note for Ana & me so that we don't forget this one)

**Comment by wpf500** [comment]
Does this mean all text will become `text-body` rather than `text-primary`, or will there still be some primary coloured text? Most newsrooms don't use the same body and primary colour and it is nice that some things are primary coloured

**Comment by aiscarvalho** [comment]
Agreed! There are indeed cases where it makes sense to have text in the primary colour (instead of the text colour).
