### ISSUE TITLE
Spec: Advanced search

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#267]
References: [spec on penpot](https://design.penpot.app/#/view/448268f0-2f80-11ed-9e6a-c67f7655c7b3?page-id=c80fd180-3502-11ed-9938-e1a5b2752cd6&section=interactions&index=0&share-id=a9628b70-3510-11ed-9e6a-c67f7655c7b3) and the [advanced search wireframes thread](https://github.com/beabee-communityrm/beabee-frontend/issues/259)

1. Advanced search panel

![image](https://user-images.githubusercontent.com/122730/191797865-6836f57b-4196-46b1-a393-1de19c1027a2.png)

![image](https://user-images.githubusercontent.com/122730/191797821-5e0e4455-2488-40ab-8c4e-8d308aa98e77.png)

2. Building a filter

![image](https://user-images.githubusercontent.com/122730/191797974-e91d8487-cce3-49c9-9de8-5ea5e73a9fad.png)

![image](https://user-images.githubusercontent.com/122730/191798065-8c9e7073-4d82-49f0-9932-87a5527ff446.png)

![image](https://user-images.githubusercontent.com/122730/191798127-4074e74d-a469-4894-b902-75f395571e41.png)

3. Results with collapsed advanced search panel

![image](https://user-images.githubusercontent.com/122730/191798250-77dc0962-d077-42e5-a496-4399515167e2.png)

4. Building complex filters with conditionals: example _all contacts who were admins until 31 Dec 2018_

![image](https://user-images.githubusercontent.com/122730/191798406-696a7ac6-ecab-4b34-a54d-c65078c47240.png)

![image](https://user-images.githubusercontent.com/122730/191798995-5812b64c-edc1-4d69-8a50-c585afceb759.png)

![image](https://user-images.githubusercontent.com/122730/191799064-1c87d96b-d745-4c46-ba6c-c8c351216aa7.png)

5. Building complex filters with conditionals: example _all contacts with 8 Km of a location_

![image](https://user-images.githubusercontent.com/122730/191799485-314ad50f-9230-44ab-8f39-484375db7180.png)

6. Saving filters as a segment

![image](https://user-images.githubusercontent.com/122730/191800655-8eb44c44-e00f-44c3-9541-dacd3e5b20d2.png)

**Comment by wpf500** [comment]
LGTM :+1:

**Comment by TobiasHauswurz** [comment]
Yes, looks very good :)
