### ISSUE TITLE
Parent child navigation

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#327]
We would propose adding a tiny breadcrumb for the purpose of parent child navigation:

*Callout overview*
![callout-overview](https://user-images.githubusercontent.com/122730/206229913-dc89e404-ba17-486c-9e09-3459ffbdca19.png)

*Editing a callout*
![callouts-edit](https://user-images.githubusercontent.com/122730/206229921-e122d65a-c2ef-4ad6-9415-b1d4bda75e1f.png)
![callouts-participate](https://user-images.githubusercontent.com/122730/206229924-4f78659d-612a-4d57-b988-cd058545d2f5.png)

*Previewing a callout*
![callouts-preview](https://user-images.githubusercontent.com/122730/206229927-010457cb-19dc-4fba-ab9e-35ab20f3ccf5.png)

*Single contact page*
![community-single-contact](https://user-images.githubusercontent.com/122730/206229930-57fa9046-973a-40a2-a3f4-7649c12acda9.png)

---

As a sidenote, when doing the mockups we noticed the preview is in Callouts but in the user menu (instead of the admin menu):
![callouts-preview_sidebar](https://user-images.githubusercontent.com/122730/206229928-709d837b-5bfa-4f37-9643-f69dd5d1b3a7.png)

**Comment by wpf500** [comment]
Looks good. My only question is what shows on the root pages (e.g. callouts, community, etc.)? If nothing does this mean the page title would move down slightly when navigating from a root page to subpage? Is this intended?

**Comment by aiscarvalho** [comment]
Maybe a simpler solution can better suit our needs at the moment.
Here are a few mocks of a **back to parent page** button, since we only need one level between parent and child page.

Editing a callout: **<- Callouts** takes you to the parent page (callout list) and **Cancel button** (takes the user to the callout detail page)
![image](https://user-images.githubusercontent.com/122730/206523638-34ccb367-5c33-4879-b400-69d9f65c8857.png)

Callout detail page:
![image](https://user-images.githubusercontent.com/122730/206523877-a32c1992-a5ab-48cc-9686-67682ed394cc.png)

Single contact page:
![image](https://user-images.githubusercontent.com/122730/206524334-f5591466-caa6-4ed4-9070-c8dc2795d064.png)

**Comment by wpf500** [comment]
I think I prefer the breadcrumb design wise. How does the button look on mobile? Does it sit above the title? How does this work with large titles where the title wraps?

**Comment by rlafuente** [comment]
Let's go with the traditional breadcrumbs then. As we see it, on mobile they'd be shown above the titles, wrapping if needed.

We've also been debating the jump that would happen from parent to child pages (where parent would be missing the breadcrumb), which could be addressed by including the breadcrumb on parent pages as well:

![image](https://user-images.githubusercontent.com/159868/207646730-a42e9f53-cabf-4a70-9b0b-f25f4d9aaabd.png)

![image](https://user-images.githubusercontent.com/159868/207646940-17631b10-f962-4d91-8aeb-63a98ddb7b61.png)

![image](https://user-images.githubusercontent.com/159868/207646957-9aab27e2-6868-4b69-a1dc-053f2339e57d.png)

How does this look to you?

**Comment by wpf500** [comment]
Love it!
