### ISSUE TITLE
Callout preview improvements

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#333]
After looking at a few examples of how other applications solve previews:
- edit and preview side by side (as our preview interface for the membership builder)
- modal window
- opening the preview in a new tab (current callout preview functioning)
- alternating between edit / preview mode
we would propose showing the callout preview in a modal window.
This will work well for showing the preview both in the callout edit interface and the callout detail page:

![Screenshot 2022-12-15 at 15-31-01 Callouts - beabee dev](https://user-images.githubusercontent.com/122730/207904597-c6941a92-76a4-47ed-bb0c-4cba30068799.png)
![Screenshot 2022-12-15 at 15-38-20 Callouts - beabee dev](https://user-images.githubusercontent.com/122730/207904615-33bbeeaa-4e20-42c5-b193-dc1f6972c5b2.png)

Modals are not our favourite interface pattern, but here they're the solution with the least amount of downsides (other than being a modal). Further ahead, if we replace the form.io editor we can consider a side-by-side (edit|preview) interface.

What are your thoughts?

**Comment by wpf500** [comment]
Hmm I can't decide what I think about this, on the one hand it's simple but on the other I like being able to see the whole page as a preview. I think we should call this done (it's Christmas after all!) as it's a good experiment with how to make preview better and stick it on the backlog for 2023.

That work for you @aiscarvalho?

**Comment by aiscarvalho** [comment]
@wpf500 absolutely! Let's discuss this again later on.
I also think what we have now will be improved by the new parent child navigation :)
