### ISSUE TITLE
Notifications review

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#343]
_[This issue has the "design specs" tag but it's not yet at the spec stage, at this moment it's a UI concept that would be turned into a spec if it's generally well received]_

We're picking up the error/warning/success notifications in order to address some current shortcomings:

- We're using various types of warning to the user: general notifications are small banners on top, form errors show in the form itself, and there's still a warning/error area next to some top-right buttons (e.g. Save draft)
- The look is not unified, with each type made to fit its specific context; the end result is disjointed

Our direction for a possible alternative would be a floating notification area on the bottom left corner:

![image](https://user-images.githubusercontent.com/159868/210834440-7eada333-aa90-4cce-a6ee-188d9c7b7cd7.png)

And on mobile, a popover:

![image](https://user-images.githubusercontent.com/159868/210833007-f87dd7d2-0bdb-452e-bcca-7c5e1ebfa162.png)

_(we used the callouts index as a quick backdrop to show the style and positioning, of course these notifications wouldn't belong here)_

- The "notification area" would be detached from the UI, and while we aren't eager to add to our UI repertoire, drop shadows seem like the natural method to visually separate layout layers.
- The spinner next to the X icon would be a countdown indicator. After some elapsed time (5-7 secs) the notification would disappear without user action. On mouseover, the countdown stops and the indicator disappears. The main purpose is to not break user flow and force people to keep closing notifications (e.g. on repeated form attempts); a minor upside is that the notification contains a small animation that helps drive attention into the message, meaning that we don't have to rely on strong contrast to bring it up.
- Animating UI parts is already on the project backlog, but here they might be of a higher priority, in order to bring attention to the notification messages
- In the mock images, we tried our hand at a form notification that could also include the individual fields with errors; this is a pie-in-the-sky idea with lots of edge cases that might be problematic to implement, but at this stage we thought it'd be appropriate to share.

Right now we wanted to put forward this notification concept for discussion and understanding how everyone feels about this significant change.

**Comment by wpf500** [comment]
I think this is the right direction, I could easily see this consolidating our three different styles into one which is great.

A few questions though:

1. Would the success notification also replace the currently inline success (currently done with `MessageBox`, e.g. update settings) or is just for non-inline (e.g. update callout)?
![image](https://user-images.githubusercontent.com/2084823/211305019-129d8680-f98b-49ee-b0ac-7b1c1bf69ad0.png)

2. I'm assuming form validation does not appear in a floating box. Does the inline error stay in this case? (with the new style)
![image](https://user-images.githubusercontent.com/2084823/211305387-6dd9d875-c8fa-4a50-a86c-f663f46e36fc.png)

3. How does this work with other form data errors such as invalid username/password on login? Does the error stay inline?
![image](https://user-images.githubusercontent.com/2084823/211306311-ee2c6892-0b58-4acf-a2c0-16c9d143970d.png)

I like general style and would apply it to all our success/error notifications with the following rules:
* Inline forms (i.e. forms that change without reloading the page) errors should appear inline, above the submit button. This includes synchronous errors such as form validation and async ones such as wrong user/pass, duplicate email address, etc. I think it's important that the error is close to the form.
* Non-inline forms should always use floating notifications for success and failure as shown in your screenshots

The one I can't decide on is success notifications for inline forms (e.g. update settings). Should the success message be floating or inline? I think I'd lean towards all success messages being floated but I'm not sure. What do you think?

**Comment by rlafuente** [comment]
I think we're in sync! The general principle would then be that we would use floating notifications for everything, except:
  - inline form errors should show next to the affected fields
  - a non-valid inline form should pop up an inline error on Submit (not 100% sure about this one, but we can just try it out and see what works best)
 
Also agree that listing the form errors on the floating notification is not practical and somewhat redundant.

We'll update the spec accordingly and post another comment once that's done.

**Comment by rlafuente** [comment]
Updated version:

![image](https://user-images.githubusercontent.com/159868/211801327-96c3f198-ac40-445f-be8c-21a8f70a1745.png)

We didn't go through all the possible variations (e.g. success notifications with title and text), as we thought it is more efficient to address the edge cases that will show up and update the spec accordingly. Do let us know if you anticipate any specific case that's not sufficiently addressed by this approach!

**Comment by wpf500** [comment]
Great, as you say we can adjust later so this looks good enough for now :+1:
