### ISSUE TITLE
Grid system

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#351]
Here is our proposal for a grid system, currently as a large PNG -- we'll try to wrangle PenPot to output a more practical format. We can review this tomorrow to clarify all details.

![grid-screens](https://user-images.githubusercontent.com/159868/214364357-e7bcd0bc-8925-42d3-8cdb-b1ad63927e41.png)

**Comment by wpf500** [comment]
A few questions:
* It looks like the footer expands into the final three columns but the header doesn't, is this the case?
* What is the difference between 2-col 1 and 2-col 2?
* Does the grid system have a max width or keep expanding?

I think I have a few other questions but struggling to express them so I will try to implement this and see what comes back

**Comment by wpf500** [comment]
The grid assumes the content width doesn't include the menu (fixed 240px), so I have changed the breakpoints to respect this. This means `lg` is now 1268px (1024px + 240px) and `xl` is 1640px (1400px + 240px).

So breakpoints and layout behaviour:
* `xs` is 450px
* `sm` is 640px (barely used)
* `md` is 760px, collapsed menu and 2 col grid _<- too small for a 3 column grid_
* `lg` is 1268px, menu expands and full grid
* `xl` is 1640px, 3 last cols unused

Questions:
* What to do with the 3 column grid on `md`?
* Two layouts are missing, what to do with them?
  1. The table view (filter menu + table), e.g. callouts, contacts.
    **Suggestion:** table expands to full width (minus three cols on `xl`)?
  2. The stepper view (steps menu + content), currently just create/edit callout. Needs columns for inputs and help text

**Comment by rlafuente** [comment]
Ah, thanks for this!

- That's what we tried to outline, but we should say we're not super sure of what will work best in practice. So for the sake of simplicity, we can go with the general 9-col width for the footer too.
- No difference -- we started with those 2 screens thinking they might require different approaches but settled on a generic 2-col layout. Sorry that it was confusing.
- ~~It should probably keep expanding. We're not sure whether a max width would be useful here, but we're more than open to consider it.~~ Don't know what i was thinking -- we're currently using a max of 1400px for the content area

**Comment by wpf500** [comment]
@aiscarvalho here is a visualisation of the layout grid as we just discussed

![image](https://user-images.githubusercontent.com/2084823/214868085-47abb639-603a-4e03-9727-56664363837d.png)

**Comment by aiscarvalho** [comment]
@wpf500 we updated the grid document. Have a look in [penpot](https://design.penpot.app/#/view/4755a563-5b43-8015-8001-eb5738f69624?page-id=4917fb75-271e-807f-8001-ffef3c43de42&section=interactions&index=0&share-id=3282141d-a293-819c-8002-000eea0c9340) and let us know if it's clearer now :)

![image](https://user-images.githubusercontent.com/122730/216650259-355d3036-5b8b-4ff8-9b23-46132676a62a.png)
