### ISSUE TITLE
Show last editor comment in callout responses

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#352]
We were missing a row for showing the last editor comment (thinking of Crowdnewsroom), and figure out how to make it work visually. We took the opportunity to review some small details that can improve UX:

- use a humanised date format (x days ago instead of absolute date)
- use a numeric ID (can be anything else, but the long hexadecimal strings take out a lot of space)

Current layout:

![image](https://user-images.githubusercontent.com/159868/214590729-1e40cfaf-ca02-44b3-bf86-54c574d85568.png)

Alternative with last comment + other changes:

![image](https://user-images.githubusercontent.com/159868/214590844-82f525ec-36c5-4a6d-b91c-f17353509ae4.png)

Alternative with an expanded comment after click:

![image](https://user-images.githubusercontent.com/159868/214590884-92db23ff-fb89-4720-bed7-4828c5734544.png)

**Comment by wpf500** [comment]
:+1: for the changes to the ID and submission date.

When we discussed this before we said we didn't want to use a column as one of the problems identified was that long comments caused the table to squash, instead doing something a bit like how we do [contact descriptions](https://user-images.githubusercontent.com/2084823/214603179-69c1d78c-4058-4667-acfc-f8def4878288.png) (but nicely styled!), e.g.
![image](https://user-images.githubusercontent.com/2084823/214602640-45fcec8b-1ec2-4694-b34c-0df413aeceda.png)


Do you think the column is a better way forwards? How would this work on smaller viewports?

**Comment by rlafuente** [comment]
Good point! Since it's a feature destined mostly for CNR, maybe it would make sense to have a checkbox to hide/show the last editor comment on all rows?

**Comment by wpf500** [comment]
Sounds good :+1:
