### ISSUE TITLE
Callout slides design

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#356]
We're still finishing up the mobile view, but here's our design for the callout slides on desktop. We've mocked up four steps:

- intro text with image
- regular question
- final screen, with unanswered mandatory questions
- regular question after reviewing the missing answers

(we wrote more about our reasoning below the pictures)

## Desktop

![image](https://user-images.githubusercontent.com/159868/216666190-9eb86421-0cd7-4cf6-b495-46adccb50a83.png)

![image](https://user-images.githubusercontent.com/159868/216666248-b188cd92-161d-4a8b-91d0-b59073fbb1af.png)

![image](https://user-images.githubusercontent.com/159868/216666321-6e10b2db-4f72-4ee6-9b0f-7efaf655aa0f.png)

![image](https://user-images.githubusercontent.com/159868/216666392-89106163-1d4a-4810-9d95-db952dbf636f.png)

## Mobile

![image](https://user-images.githubusercontent.com/159868/216664803-9e2975f4-aaa5-42da-8cbe-d88fc5387d94.png)

## Details

* Slide contents might have several questions, so the content area should be scrollable; the next/previous area and the submit button should be sticky.
* One specific point that we worked on was the UX to **go back to unanswered questions**. Last week we had tried a typeform for something, and were immediately turned off by not being able to progress through the form before answering mandatory questions. We think it'd be important to let users leaf through the form, or skip slides for later, and provide them with a simple way to review what's missing.
* The disabled "Submit" button should, when clicked, pop a warning pointing to the slide navigation. A tooltip should be enough here, but a modal will do if it's too much work.
* Another implementation detail: after reaching the final slide when there's missing answers, the "Submit" button should probably stay on every screen as users fill out the remaining answers, so that they don't need to go back to the final slide.

**Comment by aiscarvalho** [comment]
Here's a revised version of the [design spec for the callout slides](https://design.penpot.app/#/view/b7be8329-31f9-8057-8001-febc6a7a3905?page-id=b7be8329-31f9-8057-8001-febc6a7a3906&section=interactions&index=0&share-id=19015bbb-cadd-8096-8002-015757b898ed).

Callout page before starting to reply:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/c6959615-d296-4249-9eb6-131cc1fc1a26)

**Callout slides main changes:**
- form fields are aligned to the left
- progress is shown in an horizontal bar; this way we can quickly adjust progress for callouts with different paths
- mandatory questions need to be filled before we allow the user to proceed

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/87859d29-8c7c-43cf-b88e-b23c5cfba0b7)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/f58da60a-4d2d-40b3-b197-671c92aa9f17)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/402c6e00-3b80-49bd-98d1-81d43edf9217)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/04b0479a-f831-4898-b831-4811ed470ff7)

Mobile layout:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/575c7aaa-44c2-4aa3-a29b-e8462cc6081c)

**Comment by wpf500** [comment]
@aiscarvalho I'll give this a go and see how it feels when it's live :+1:.

I like the more "continuous" progress bar feel but have some concerns about how it would work in practice. However for the MVP I'm not going to be able to implement it in any case so we can discuss it further at a late date
