### ISSUE TITLE
Callout response "settings" page

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#419]
First draft of the callout response settings page:

Settings button in callout responses page:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/6560c54a-6137-45e4-aece-8bd0602fb8b8)

Settings page: 3 column layout for managing folders, tags and reviewers.  
We used the existing design pattern but switched the position of the "add new" button to the top of the list, to prevent it from being hidden. The **inbox** folder has no delete button because there should always be at least one folder that holds all responses.
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/a4318a49-4977-4a73-868f-4a7db85ba8c2)

Settings page with "Add new" open. We also added a drag to the folder list as a future nice-to-have:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/bc755353-89bb-46cd-97eb-82dadea699ec)

[Link to spec in penpot](https://design.penpot.app/#/view/88d87192-d205-8007-8002-978e0fd9d013?page-id=88d87192-d205-8007-8002-978e0fd9d014&section=interactions&index=0&share-id=7f77885c-d0bf-8175-8002-b2dd329ea9f4)

**Comment by wpf500** [comment]
The settings page looks good but I'd like to understand what your thinking is behind the location of the settings button.

At the moment that top right spot is used for actions:

Action 1: Add a [callout/contact/notice]

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/59f1adcc-dd65-475c-be1d-53344a43b50b)

Action 2: Update (either to save as draft, or publish, or preview) a callout 

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/58e57dd2-5c06-4c15-9811-095b192c16dc)

In both cases it's applying an action to the "entity" you are looking at.

This settings links feels like a new use and I want to understand how it works alongside the primary use. For example, we will need a settings page for contacts too (to define the tags, manage segments, etc.). Is your thinking that such a link would sit next to "Add contact"?

**Comment by aiscarvalho** [comment]
We agree this is not the most ideal placement for the settings button but also agreed to keep it here while we sort the table filters and view options.

The button style and icon is updated:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/6bf1cf21-c92c-4d6a-8cf0-d3413792d404)

**Comment by wpf500** [comment]
:+1:
