### ISSUE TITLE
Fix checkbox and label alignment

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#44]
Adding here notes on the correct label+checkbox layout after looking at the join form:
- the checkbox should be aligned to the baseline of the label text
- the text shouldn't wrap around the checkbox
- margin between checkbox and text is 4px

Screenshots from the current checkboxes, taken from join and setup pages (the join label is edited to be longer, to show the text wrap);
and one screenshot of the checkbox from the design spec for reference.

![checkbox-join](https://user-images.githubusercontent.com/122730/141324180-ea0ec550-aeb4-4239-bbed-7d87fbac52cd.png)
![checkbox-setup](https://user-images.githubusercontent.com/122730/141324204-b7cf72f0-017a-4ad6-a87b-f92a00b34cec.png)
![checkbox-spec](https://user-images.githubusercontent.com/122730/141324221-30b79e79-b907-4b79-8377-27b240de6863.png)

**Comment by basilesimon** [comment]
Hey @aiscarvalho, the layout appears to be different since you filed this issue – my apologies if I'm looking in the wrong place!

![image](https://user-images.githubusercontent.com/5701152/152943947-06b7d35e-706e-431a-b8f2-3ab227c1db2d.png)

I do notice that we're still missing that small 4px margin, but I'll wait for you to get back to this issue before pushing a fix.

**Comment by aiscarvalho** [comment]
Hello @basilesimon!

Thanks for your comment :)

The misalignment is sort of a cross-browser issue since, at the moment, we're using the browser default checkbox. It's true it's nicely aligned in your screenshot. Did you check this in dev or a specific branch?

Here's a screenshot from dev, and I added more text to show how the label wraps around the checkbox, when there are multiples lines of text:
![image](https://user-images.githubusercontent.com/122730/153451973-76c55a66-9231-47de-9351-fa2686eaafb4.png)

**Comment by basilesimon** [comment]
Cheers @aiscarvalho – which browser is this, so I have a play with this too? 

As you mention, if it's browser-specific it might be annoying to address the alignment. The wrapping of the copy around the checkbox, however, I'll be able to sort shortly.

**Comment by aiscarvalho** [comment]
@basilesimon good call. I'm running Debian, and the screenshots above are from FF 78.14.0.
