### ISSUE TITLE
Thank you message for callouts

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#453]
In order to address the "thank you" message which doubles as a status indicator, we settled on a notification-like area above the title to ensure that it is properly visible.

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/322a3e69-6ff8-4a2f-bcec-b274888624f8)

Different messages for each possible state:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/7fc94837-c299-42ff-a2f2-304edfaebd4f)

**Comment by wpf500** [comment]
I think the notification-like area works well to indicate a callout has ended, but I can't really see the value in it for the other states (open editable, open non-editable). Can you explain your thinking? Are we dropping the status indicator (below)?

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/2084823/a05776dd-87ff-4a2e-8091-0c247c177c2e)

**Comment by aiscarvalho** [comment]
We designed a new spec to address the callout status and thank you message.

We reorganised the elements below the callout title to make the status clearer but also to highlight the possible actions:
- open and unanswered callouts: participate or continue callout (if the user started to reply but didn't finish)
- open and answered callouts: see my response; edit (if allowed); submit another (if multiple answers are allowed)
- ended and answered callouts: see my response
- ended and unanswered callouts: no actions, instead we show an informative message _This callout ended on DD/MM/YYYY. Participation is closed._

The thank you message is displayed as a notification after successfully submitting a response.

This is our first draft, from last week, featuring a [two column layout for callout image and description](https://design.penpot.app/#/view/508641bb-11c9-806c-8003-0cf1cac6273a?page-id=508641bb-11c9-806c-8003-0cf1cac65f69&section=interactions&index=0&share-id=5b5d7f5d-3b58-8033-8003-0d11abaafeba)

After discussion we updated the spec to keep the current callout layout, [a single column with full width image and text below](https://design.penpot.app/#/view/508641bb-11c9-806c-8003-0cf1cac6273a?page-id=45f1c52f-b1d0-80ef-8003-15f62085aae3&section=interactions&index=0&share-id=4219d288-8754-803c-8003-15f728c21439)

**Open and unanswered:**
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/239b7474-d657-4e6d-8f7b-c0b7cdd61b42)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/56718e81-7837-457f-a592-f4da71d46c24)

**Open and answered:**
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/56634714-08d9-4614-bcfc-f38f95912ee4)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/a473ed6d-2ad7-4b18-81e5-21a2d8f388ce)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/b1d5e553-3fab-492c-bbaf-866103663c4e)

**Ended and answered:**
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/4256cbb0-f481-4c2b-81e3-565cc78216a3)

**Ended and unanswered:**
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/d36fa5bb-253d-4d04-8d2c-69850e1486e2)
