### ISSUE TITLE
Spec for optional contribution in signup flow

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#490]
A design proposal to include the option become a member without making a contribution in the join form.
When the user selects this option the contribution and payment method sections are disabled and the bottom button text updated:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/3365ec21-4555-4b53-b004-e6e67f122459)
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/3208a060-d6f3-4bf0-bb03-ea1e1622c3ed)

**Comment by wpf500** [comment]
:+1:
