### ISSUE TITLE
Connect call-out answers and user profiles - stage 1

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#516]
Some sketches for including callout answers in our filtering menu, in the contacts page:

When building a filter the admin can now select **Callout responses** (Contact data would be the default for filters):
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/fad2dfa6-3a46-4bf6-8c8f-dfb465535bba)

Next step would be to select the Callout and pick a question to create a filter:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/3b2c3e5e-1ecd-4bcb-8e33-0f710baeece9)

Alternative UX with the option to display the answer to the selected question in the contacts table:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/f4f6c112-f7d3-4004-836f-1795e18c1b94)

Contact table filtered by callout answer. From here the admin can tag/export/create a new segment (and in the future send a message):
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/0c1f1b59-2214-406e-bf43-a4513e9cef29)

Alternative Contact table showing the answer to the selected callout question:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/3e0fd61b-0b18-44d6-a6b5-b2bc28cd7846)

[Penpot spec](https://design.penpot.app/#/view/aba078d3-8498-80bd-8003-6fe2c6900382?page-id=aba078d3-8498-80bd-8003-6fe2c6900383&section=interactions&index=0&share-id=c29b5282-da70-8012-8003-6ff13fe1a5f2)

**Comment by TobiasHauswurz** [comment]
I think this is great first attempt! Some thoughts, questions and concerns: 

- I don't see a possibility to only search for if someone took part in a callout in general, not searching for the answer to a specific question. I think, this would be a quite important feature.
- Will I be able to combine contact data and callout responses in one search? (So when I click on add rule, can I decide if I want to filter contact data or response data again?)
- Some questions could be quite long (always depends on how a newsroom uses the "label" in the callout). Does it still fit into the dropdown then? 
- Will the "show answers in table" stay active when I save as segment until I turn it off again?
- The table looks quite different in this spec. Is the idea to replace it with this new design for this feature? If yes: thumbs up, I think it looks great :)
- If we go with the filtering approach, I think bulk tagging in the database becomes quite an important feature.

**Comment by aiscarvalho** [comment]
We updated the spec based on the feedback we got:

More selectors, larger dropdowns and removed the option to show responses in the table
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/fcbdb1d1-dc88-41db-8a38-1812fdcc6932)

Added an example of a combined filter to show how it would look. @TobiasHauswurz yes, the idea would be to allow a combination of filters with different selectors:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/d483746d-53c1-4f39-9d19-16a2b03ce7ac)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/a61dc317-fe88-48a6-9bbb-cc4d7e5719b4)

The contact table layout follows the updated design from the [Show options for tables spec](https://github.com/beabee-communityrm/beabee-frontend/issues/423) :)
We organised the selectors in the following order: Contact information / Contribution / Role / Join Survey / Callout responses. And we had proposed "Contact information" as the default selector when creating a filter. Let us know if we should change the order and/or default selector according to what is most useful for an admin.

We've just added a quick mock of a filter by callout participation:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/ebe0966c-f963-4699-98e5-d174caed4c7a)


[Link to penpot spec](https://design.penpot.app/#/view/aba078d3-8498-80bd-8003-6fe2c6900382?page-id=aba078d3-8498-80bd-8003-6fe2c6900383&section=interactions&index=5&share-id=c29b5282-da70-8012-8003-6ff13fe1a5f2)

**Comment by wpf500** [comment]
Done :+1:
