### ISSUE TITLE
User view response filters

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#521]
A mockup for a filter interface in the callout map view.
The filter button is placed near the search box, when clicked it would display the available filters in the left side panel.
When the filter panel is closed, active filters are shown using a similar pattern to the one we use in the table filters:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/c1b7bebe-daac-4ad7-ac5d-3b2a8814f8e5)

Desktop flow:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/46b1eadb-671b-4c44-b265-0ef43c00574c)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/53aabe32-f6c4-4d6d-a8d5-6c9b72c73400)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/a6119f64-d860-4f3c-a47c-45d9dbe9f79d)

[Penpot](https://design.penpot.app/#/view/af8aaf7c-05e6-8124-8003-82243d0f16ee?page-id=8a5a6014-1987-80eb-8003-8375beab36c8&section=interactions&index=3&share-id=75aa5258-9a82-8002-8003-8387334d38e7)

**Comment by wpf500** [comment]
Looks great :+1:
