### ISSUE TITLE
Telegram callout flow

### ISSUE THREAD

**Issue by rlafuente** [beabee-communityrm/beabee-frontend#524]
The wireframes and design docs for this are in this [PenPot board](https://design.penpot.app/#/view/af8aaf7c-05e6-8124-8003-8b3c56d8173e?page-id=af8aaf7c-05e6-8124-8003-8b3c56d8173f&section=interactions&index=0&share-id=75aa5258-9a82-8002-8003-943d21e6c477)

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/159868/3be147b7-60ea-4af5-953b-7cff414b5020)

**Comment by JumpLink** [comment]
@wpf500 @rlafuente I find the wireframes very useful and I assume you have also incorporated user feedback into them? Do we want to start implementing this further or arrange a meeting where we discuss what should be implemented next?

**Comment by rlafuente** [comment]
No, not yet -- updating the wireframes is a non-trivial task and needs to be accounted for in our planning. We can consider that for the next sprint, if priorities allow. We're adding a card for this on the backlog
