### ISSUE TITLE
Mobile view for tabs

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#530]
Currently the tabs are displayed as a dropdown:
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/fc9a9ec9-b882-449e-bbd2-190e0b464730)

Here's a proposal to replace the dropdown interface: an horizontal scrollable bar to display the horizontal tabs
![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/d12f1f71-3fbc-4dca-aff3-d22bac5f8a25)

While designing the mockup we updated other elements in the mobile layout:
- removed the breadcrumb to free vertical space
- added the icon to the main title in the top navigation (Contacts)
- "add contacts" shifted to bottom right corner, as a floating button
- updated table actions to match the latest spec

[Link to penpot](https://design.penpot.app/#/view/1555ffb0-ea21-11eb-9b24-4c4b7a420f0b?page-id=fa8fe1bf-8fa0-80b3-8003-ca4c9c952b7f&section=interactions&index=0&share-id=af8aaf7c-05e6-8124-8003-ca56ba848c7a)

**Comment by wpf500** [comment]
Looks good to me, but I will separate out the different changes into different cards for implementation

**Comment by wpf500** [comment]
One question actually: if you've hidden the breadcrumb on mobile view then we no longer have an easy way to go back from callout responses to the callout (for example), how can we retain this functionality?
