### ISSUE TITLE
UI for editing bot messages

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#531]
A new tab in _Settings_ to edit the telegram bot profile information and introductory message:

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/d06b1dcd-794e-4bd5-b49a-28c0b559bba6)

We included a field to edit the bot profile image. By default, we'll show the existing logo and, if technically possible, we allow the admin to use a different profile image for the bot.

![image](https://github.com/beabee-communityrm/beabee-frontend/assets/122730/66314d3c-8f9e-41af-a438-575d7b9964bb)

[Penpot](https://design.penpot.app/#/view/aad80030-0828-11ed-9552-f940e3befd53?page-id=004b59fb-edf1-803d-8003-cb93ea48a041&section=interactions&index=0&share-id=75aa5258-9a82-8002-8003-cba3fba1f415)

**Comment by wpf500** [comment]
LGTM :+1:
