### ISSUE TITLE
Amount component: fix button selected and hover state colors

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#73]
The amount component, used in the join form and the contribution page, is missing hover state in the buttons (monthly/annual and amounts) and has a selected state is different. These buttons follow the "highlighted button outline" style ([link to design system page](https://design.penpot.app/#/view/1555ffb0-ea21-11eb-9b24-4c4b7a420f0b?page-id=1555ffb1-ea21-11eb-9b24-4c4b7a420f0b&index=5&section=interactions)) -- adding a screenshot of the relevant part for quick reference (normal/hover/disabled states):
![image](https://user-images.githubusercontent.com/122730/144467227-cdce7355-e4cc-45f7-8ac0-c1d4824f0c47.png)

A screenshot of the component in the [contribution page](https://design.penpot.app/#/view/bf28f200-e971-11eb-9b24-4c4b7a420f0b?page-id=36a18270-e972-11eb-b4d3-978aa0906fd6&index=0)
![image](https://user-images.githubusercontent.com/122730/144464933-89959f0d-1061-4b50-9170-61e682160659.png)

**Comment by wpf500** [comment]
@aiscarvalho can this be closed now?

**Comment by aiscarvalho** [comment]
Yes!
