### ISSUE TITLE
Integrate Thank you message in footer

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/beabee-frontend#87]
Include the "Thank you" message, shown in the user homepage, in the footer with a more compact layout (since it would become visible in all pages).

Attaching a quick mockup to show how it would look:
- the logo could be replaced with a <3 icon if we find it repetitive to have the logo in the sidebar and the footer
- ignore the colours in this mock: all links in footer should have colour link and all texts should have text colour

![image](https://user-images.githubusercontent.com/122730/150374031-2119ac82-a022-4218-832c-b47931899e46.png)

**Comment by wpf500** [comment]
Sorry I missed this one. This will need a change to the API so the thank you message is loaded on every page, will add to the backlog.

**Comment by wpf500** [comment]
We have had the thank you text hidden for so long that we decided to remove it. It's one less thing for admins to write copy for and we felt was never that useful anyway. @aiscarvalho @rlafuente feel free to reopen if you think differently
