### ISSUE TITLE
Numbers are cut off at bottom 

### ISSUE THREAD

**Issue by saschafoerster** [beabee-communityrm/beabee-frontend#90]
Somehow the numbers are not fully visible. 
<img width="449" alt="Bildschirmfoto 2022-01-21 um 17 25 36" src="https://user-images.githubusercontent.com/1153741/150563352-f2015f61-692f-494a-bdc5-ec956493a067.png">

**Comment by saschafoerster** [comment]
Same in the backend  ./profile/contribution

<img width="396" alt="Bildschirmfoto 2022-01-21 um 17 27 47" src="https://user-images.githubusercontent.com/1153741/150563693-10d77d1e-6255-44ea-ac54-84cecb5acf10.png">

**Comment by basilesimon** [comment]
Seems to me that the `<div.relative>` containing the number and its shadow `input` aren't dealt with very well in Safari (the only browser I can reproduce this bug on).

Very slightly tweaking the line-height of the `<div.text-6xl>` helps but does not feel very tailwind-y.
Alternatively, adding a bit of padding-bottom on the `<div.relative>` causes the baseline to go out of the window, and the number to hang a bit... which we may or may not be fine with.

**Comment by saschafoerster** [comment]
Indeed, I saw this in Safari, sorry for not describing it in more detail before! 

PS: Isn't it that Safari users pay more? 😇

**Comment by wpf500** [comment]
Fixed by #504!
